// src/context/DetectionContext.jsx

import { createContext, useState, useContext } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const DetectionContext = createContext();

export function DetectionProvider({ children }) {

  const [history, setHistory] = useState(() => {
    try {
      const saved = localStorage.getItem('detectionHistory');
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  const [currentResult, setCurrentResult] = useState(null);

  // ----------------------------
  // History
  // ----------------------------
  const addToHistory = (result) => {
    if (!result) return;

    const newHistory = [result, ...history].slice(0, 50);
    setHistory(newHistory);
    localStorage.setItem('detectionHistory', JSON.stringify(newHistory));
  };

  const clearHistory = () => {
    setHistory([]);
    localStorage.removeItem('detectionHistory');
  };

  // ----------------------------
  // JSON Download
  // ----------------------------
  const downloadJSON = (result) => {
    if (!result) return;

    const data = JSON.stringify(result, null, 2);
    const blob = new Blob([data], { type: 'application/json' });

    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');

    a.href = url;
    a.download = `fakeout-result-${result.timestamp || Date.now()}.json`;
    a.click();

    URL.revokeObjectURL(url);
  };

  // ----------------------------
  // PDF Download
  // ----------------------------
  const downloadPDF = async (result) => {
    if (!result) return;

    try {
      const reportDiv = document.createElement('div');

      reportDiv.style.width = '800px';
      reportDiv.style.padding = '20px';
      reportDiv.style.backgroundColor = 'white';
      reportDiv.style.color = 'black';
      reportDiv.style.fontFamily = 'Arial, sans-serif';

      reportDiv.innerHTML = `
        <h1 style="color:#f59e0b;">FakeOut AI Detection Report</h1>
        <hr/>

        <p><strong>Filename:</strong> ${result.filename || 'Unknown'}</p>
        <p><strong>Timestamp:</strong> ${new Date(result.timestamp).toLocaleString()}</p>
        <p><strong>Verdict:</strong> ${result.verdict?.toUpperCase()}</p>
        <p><strong>Confidence:</strong> ${result.confidence}%</p>

        <h3>Model Breakdown</h3>
        <ul>
          <li>MFCC + XGBoost: ${result.model1?.prediction} (${result.model1?.confidence}%)</li>
          <li>wav2vec2: ${result.model2?.prediction} (${result.model2?.confidence}%)</li>
        </ul>

        <h3>Explanation</h3>
        <p>${result.explanation || 'No explanation available'}</p>

        <hr/>
        <p style="font-size:12px;">Generated by FakeOut AI</p>
      `;

      document.body.appendChild(reportDiv);

      const canvas = await html2canvas(reportDiv, { scale: 2 });
      const imgData = canvas.toDataURL('image/png');

      const pdf = new jsPDF('p', 'mm', 'a4');

      const imgWidth = 210;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      pdf.save(`fakeout-result-${result.timestamp || Date.now()}.pdf`);

      document.body.removeChild(reportDiv);

    } catch (error) {
      console.error('PDF generation failed:', error);
    }
  };

  // ----------------------------
  // Provider
  // ----------------------------
  return (
    <DetectionContext.Provider value={{
      history,
      currentResult,
      setCurrentResult,
      addToHistory,
      clearHistory,
      downloadJSON,
      downloadPDF,
    }}>
      {children}
    </DetectionContext.Provider>
  );
}

export function useDetection() {
  return useContext(DetectionContext);
}